name: neighborhood
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.16.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  http: ^1.6.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ==========================================
  # ALAT PEMBUAT LOGO APLIKASI
  # ==========================================
  flutter_launcher_icons: ^0.14.2

# ==========================================
# PENGATURAN LOGO APLIKASI (NAMA DIPERBARUI)
# ==========================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Mendaftarkan folder assets agar gambarnya bisa dibaca
  assets:
    - assets/